import Head from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </>
  );
}
