import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../component/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    //   <div className="grid gap-4 grid-rows-1">
    //     <div>
    <section>
      <Header></Header>
      {children}
    </section>

    // </div>

    //   </div>
    // </html>
  );
}
